---
- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted

- name: daemon_reload php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    daemon_reload: yes
    state: started

- name: restart blackfire-agent
  service:
    name: "{{ php_blackfire_daemon }}"
    state: restarted
  when: not php_blackfire_test_mode
